---
version: '3.7'
services:
  db:
    image: postgres:12
    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: 123 # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default
    networks:
      - default 
  speter:
    build:
      context: .
      dockerfile: Dockerfile.development
    tmpfs:
      - /tmp
    ports:
      - "3000:3000"
    volumes:
      - .:/app
        #      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
        # - rails_cache:/app/tmp/cache
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails s -b 0.0.0.0"
    environment:
      - BINDING=0.0.0.0
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - HISTFILE=/app/log/.bash_history
      - NODE_ENV=development
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
      - PSQL_HISTFILE=/app/log/.psql_history
      - RAILS_ENV=${RAILS_ENV:-development}
      - RAILS_LOG_TO_STDOUT=true
      - WEB_CONCURRENCY=1
    networks:
      - default
volumes:
  bundle:
  node_modules:
  rails_cache:
  packs:

# networks:
#   default:
#     name: default
